version: 2
jobs:

  #default values for all jobs
  defaults: &defaults
    docker:
      - image: circleci/node:latest

  setup_dx:
    <<: *defaults # call default at the start of each job
    steps:
      - checkout
      - run:
        name: Install SFDX CLI
        command: . build/install.sh
      
      - run:
        name: Authenticate DevHub
        command: . build/authorize-org.sh

  create_scratch_org:
    <<: *defaults
    steps:
        - run:
          name: Create scratch org
          command: . build/create-scratch-org.sh
  
  build_source:
    <<: *defaults 
    steps:
      - run:
        name: Push source and run all tests
        command: . build/test.sh

workflows:
  version: 2
  validate:
    jobs:
      - setup_dx:
          filters:
            branches:
              only:
                - /feature-.*/
                - /packaging-.*/
                - packaging
                - develop
      - build_source:
          requires:
            - setup_dx # setting up sfdx is necessary to push the source to scratch org
            - create_scratch_org
          filters:
            branches:
              only:
                - /feature-.*/
        