version: 2

#default values for all jobs
defaults: &defaults
  docker:
    - image: circleci/node:latest

jobs:
  setup_dx:
    <<: *defaults # call default at the start of each job
    steps:
      - checkout
      - run:
          name: Install SFDX CLI
          command: . build/install.sh
      
      - run:
          name: Authenticate DevHub
          command: . build/authorize-org.sh
      - persist_to_workspace:
          # This is an important step. If we don't store the project data (cloned GitHub source and node_modules from the CLI installation)
          # we'd have to re-run installation for every workflow step.
          #
          # Also this step is crucial as we use it to share sfdx config parameters between steps.
          root: ~/
          paths:
              - .sfdx/*
              - project/*
              - node_modules

  create_scratch_org:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Create scratch org
          command: . build/create_scratch_org.sh
  
  build_source:
    <<: *defaults 
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Push source and run all tests
          command: . build/test.sh

  create_package:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Create package
          command: . build/create_package.sh

workflows:
  version: 2
  validate:
    jobs:
      - setup_dx:
          filters:
            branches:
              only:
                - /feature-.*/
                - /packaging-.*/
      - create_scratch_org:
          requires:
            - setup_dx
          filters:
            branches:
              only:
                - /feature-.*/
                - /packaging-.*/
      - build_source:
          requires:
            - create_scratch_org
          filters:
            branches:
              only:
                - /feature-.*/
      - create_package:
          requires:
            - create_scratch_org
          filters:
            branches:
              only:
                - /packaging-.*/
        